name: Test backup pipeline

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run backup script
        run: |
          echo "Uruchamiam backup danych"
          ./scripts/backup.sh
